# Generated by Django 5.2 on 2025-04-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooluser',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('a_positive', 'A+'), ('a_negative', 'A-'), ('b_positive', 'B+'), ('b_negative', 'B-'), ('ab_positive', 'AB+'), ('ab_negative', 'AB-'), ('o_positive', 'O+'), ('o_negative', 'O-')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='schooluser',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
        ),
        migrations.AlterField(
            model_name='schooluser',
            name='user_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
